import os
import json

def save_final_markdown_report(report_text: str, output_path: str):
    """Saves the final narrative Markdown report generated by Gemini."""
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(report_text)
        print(f"[Report] Final narrative report saved successfully to: {output_path}")
    except Exception as e:
        print(f"⚠️ Failed to save final markdown report: {e}")
